### ISSUE TITLE
bug: thermocycler module controls for lid and block both trigger the lid command when active

### ISSUE THREAD

**Issue by sakibh** [Opentrons/opentrons#10021]
# Overview

When the lid and block of the thermocycler is active, clicking `deactivate lid` or `deactivate block` trigger the `thermocycler/deactivateLid` command type. The triggers need to be refactored so that the button onClicks are aware which command should be triggered.

![image.png](https://images.zenhubusercontent.com/6154c951ac0872284952320b/4dac683a-1fcd-4a5b-a540-3c1bd509d771)

# Steps to reproduce

- Run the robot-server and open the app in a dev environment. Then visit the `Devices` page to access the module controls.

**Comment by mikecardarelli** [comment]
Block on receiving lid heating statuses from the robot server

**Comment by mcous** [comment]
I don't think it's correct to say this issue is blocked by the lack of "heating"/"cooling" status for the lid. If the UI needs to know whether the lid heater is _enabled_ or _disabled_, it should look for the presence of the `data.lidTargetTemperature` in the modules response. If it is set, the lid is enabled and a `deactivateLid` command is appropriate. If the field is not present, the lid is deactivated and a `setTargetLidTemperature` is appropriate.

(The same is true for the block via `data.targetTemperature`)
