### ISSUE TITLE
5.1 Feedback:  Feedback from KL

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10130]
### Serial number and name are the same.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/165942345-0fe9bb4b-ced5-4925-9385-3a19cfc4cae1.png">

### If I am only connected to one robot, why do I select which robot I am going to run on?
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/165943267-990e09f1-6bc7-4aa1-9f87-77fe575f5184.png">

### “Clear Protocol” functionality is really confusing. Clear Protocol of what exactly?
![image](https://user-images.githubusercontent.com/502770/165943046-fa032555-4d34-4361-9454-04fb6d32b876.png)

### Under devices, the “Run a Protocol” button is greyed out. Why?
![image](https://user-images.githubusercontent.com/502770/165943646-e9dd9d24-0c9a-4bff-bcec-48c49b3f4c1d.png)

**Comment by nusrat813** [comment]
Serial number and name are the same - expected behavior, run an ot2 through factory tools. check if change name is changing serial number - @nusrat813

If I am only connected to one robot, why do I select which robot I am going to run on?
- when the slide out opens first one should be selected - @mikecardarelli 
no slide out for only 1 robot - in scope for 5.3 

 clear protocol - uncurrent the run, modal in scope for 5.1
 
 Under devices, the “Run a Protocol” button is greyed out. Why? - confirm with design

**Comment by nusrat813** [comment]
Under devices, the “Run a Protocol” button is greyed out. Why? - check it was missed being implemented

**Comment by emilywools** [comment]
i synced with KL to better understand her feedback and need to go back to the team to strategize next steps.

**Comment by mikecardarelli** [comment]
Ticket for the robot selection feature https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/10173

**Comment by emilywools** [comment]
ticket for collapsing all set up for run accordions by default: https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/10179

**Comment by emilywools** [comment]
working on a potential solve for the Close Protocol feedback now
