### ISSUE TITLE
spike(robot-server): research storing protocol files in SQL

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#11015]
## Overview

In the robot server, there are two sources of truth for persisted protocol resources:

- The SQL database
- Protocol files on disk

Keeping these two sources connected and sync has proven a little fraught. Instead of persisting protocol files on disk, we could choose to persist them as blobs in the SQL database instead.

## Acceptance criteria

- Cost/benefit analysis of SQL blob storage over filesystem in terms of:
    - Code organization and structure
    - Data integrity
    - Performance
- If cost/benefit analysis is positive, prototype and proposal of a new system

## Notes

- There are avenues we could explore to run protocols directly from SQL, but temporarily dumping to files to disk for the run itself is also an option
- Any solution should not block future implementation of nested directories as part of a protocol's file structure

**Comment by SyntaxColoring** [comment]
Things we might want to check:

* Writing to our SQLite database will hold a very coarse-grained (database-wide?) lock for the duration of the transaction. This will block concurrent reads, even if they're unrelated. So we should make sure uploading a large protocol won't lock up the database for too long. The worst case is probably a big JSON protocol with lots of labware.
* With plain files, JSON parsing has the advantage that it can use [`json.load()`](https://docs.python.org/3/library/json.html#json.load) instead of [`.json.loads()`](https://docs.python.org/3/library/json.html#json.loads), which is theoretically faster because it doesn't have to buffer the entire string contents into memory. Does this matter? Would we be okay with giving it up?
