### ISSUE TITLE
6.0 Feedback: LPC: Add space between the xyz gray box and "need to make an adjustment" text

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#11061]
### Overview

if the "make an adjustment" text needs to wrap to 2 lines on LPC, add space between the gray box and the "make an adjustment" text.

current state:
<img width="1136" alt="Screen Shot 2022-07-08 at 1 32 41 PM" src="https://user-images.githubusercontent.com/4339860/178046344-edc44045-35a6-4a2c-bf6e-6e71c372ecc6.png">

design:
<img width="420" alt="Screen Shot 2022-07-08 at 2 04 30 PM" src="https://user-images.githubusercontent.com/4339860/178046516-2ad423a9-5ac2-4555-9c14-2eba15ebb4ac.png">

**Comment by koji** [comment]
@emilywools @mmencarelli 

When users open LPC with the width of more than 1010px, actually the app has space between the offset and the text.
But at less than 1000px, the app loses space.

https://user-images.githubusercontent.com/474225/179288469-3c3c31fe-682f-4cfd-81af-ac4107198e4b.mov


I guess the ideal solution would be shrinking text that we don't have. (In the future we would be able to have since we talked about that a little bit in the design <> dev meeting on Thursday)

I think a simple workaround would be adding margin-right and margin-left to the text `make an adjustment?`

add 8px margin and the image's window width is 825px
![Screen Shot 2022-07-15 at 2 38 46 PM](https://user-images.githubusercontent.com/474225/179290184-0567f871-425e-4db2-8b41-95fb58a14687.png)


Any thoughts?

**Comment by koji** [comment]
@emilywools @mmencarelli 

This keeps the same white-background size as well as the above content.
![Screen Shot 2022-07-18 at 10 53 59 AM](https://user-images.githubusercontent.com/474225/179540259-280759ee-5d1e-4c51-91ac-3dd19e49a970.png)

![Screen Shot 2022-07-18 at 11 05 46 AM](https://user-images.githubusercontent.com/474225/179542164-2d5f19c3-6e33-4e4d-b398-0ffe560e4997.png)


This is almost the same as the first one. The difference is no bottom margin.
![Screen Shot 2022-07-18 at 10 54 26 AM](https://user-images.githubusercontent.com/474225/179540581-b2702a85-b050-480c-b8f9-16933999dc53.png)

![Screen Shot 2022-07-18 at 11 04 12 AM](https://user-images.githubusercontent.com/474225/179541881-b90744cc-cb76-4573-9fc6-3ff1e476d9d9.png)

**Comment by emilywools** [comment]
imo this is good for an interim solution (until we reskin LPC!)

**Comment by koji** [comment]
This has been closed the above PR
