### ISSUE TITLE
Hardware_manager and move_to- Being deprecated?

### ISSUE THREAD

**Issue by jweinacht** [Opentrons/opentrons#11170]
I am making use of the hardware.move_to functions to move the robot to certain locations. It works quite well, but I do see the message that the function will be deprecated in later versions and to use with caution. I am (successfully) moving the robot to positions that do not easily fit into creation of a custom labware definition, as I have added several 3 small instruments that each cover more than a deck slot. I am doing this control through a downloaded program that makes use of opentrons_execute as my application is not well suited to run with the Opentrons app. So my request is to still have a way within the software to move the mechanisms without requiring a labware definition to exist for that move to be possible. I understand the risks and concerns with using this approach but using this feature is quite helpful.

**Comment by ecormany** [comment]
Hi @jweinacht, thanks for inquiring about this. We've recently published [updated documentation on moving the robot](https://docs.opentrons.com/v2/robot_position.html#independent-movement) with methods in the Python Protocol API. To future-proof your code, you may want to transition to using `InstrumentContext.move_to` instead of `hardware_control.api.API.move_to`. You should be able to use it to move anywhere on the deck (including non-labware positions — set the reference point of the target location as `None`). If you have trouble you can contact Opentrons Support, or if you find any bugs you can log them here on GitHub.
