### ISSUE TITLE
bug: Missing deck_calibration.json and robot_settings.json

### ISSUE THREAD

**Issue by aperkins19** [Opentrons/opentrons#11484]
### Overview

Hey Devs :)

The robot is not remembering "labware offset" settings.

When I calibrate it through the GUI (i.e. import a protocol file, adjust the calibration to the specific labware, "apply labware offsets" and then run the protocol) it works fine and visibly, the robot is clearly remembering those settings - both deck calibration and specific labware.

However, 

Due to our protocols being highly dynamic, we run scripts with accompanying files ( .py & .json) that need to be read in. We transfer them all into a subdirectory in */user_storage* and `opentrons_execute`.

This works fine except that doing so yields the following warning before the protocol runs:

![image](https://user-images.githubusercontent.com/57664108/191254023-99c46fbc-61d6-4e63-9d6b-70de0c1af95f.png)

As you can see, the system can't see the required: `deck_calibration.json` and `robot_settings.json`.

Lets look at the contents of *\data*:

![image](https://user-images.githubusercontent.com/57664108/191254519-150bdcb0-79c0-42f0-a338-5062e30fe198.png)

Presumably these files are written every time you do a deck cali or labware offset adjust.

I'm not sure why these files are A) not being written or B) not persisting.

Please help :) 

*p.s. can this in Advanced Settings help?*

![image](https://user-images.githubusercontent.com/57664108/191255984-946b3c06-fc9b-413a-82e6-0e58641a543c.png)

## Extra info

*Connecting to OT2 via USB*

OT2 info:

![image](https://user-images.githubusercontent.com/57664108/191255154-03bd8fde-0606-4f69-8c48-8e2c21ea82c2.png)

The directory with the files:

![image](https://user-images.githubusercontent.com/57664108/191255617-bcc02349-ae56-43bd-82c6-349dd0dc4612.png)

### Expected behavior

It would be really useful for us to able to perform a deck cali and protocol specific labware offset from the terminal.

### Operating system

Windows

**Comment by aperkins19** [comment]
I tried stopping the opentrons-robot-server:

![image](https://user-images.githubusercontent.com/57664108/191271143-87059cf7-ab27-47f7-b8ef-9ce6702f53b8.png)


But it didn't help :')

**Comment by mcous** [comment]
@aperkins19 these log warnings are from old settings files that are no longer used and can be ignored. Labware offsets are not persisted outside the scope of an individual run as of `v5`.

> *p.s. can this in Advanced Settings help?*
> 
> ![image](https://user-images.githubusercontent.com/57664108/191255984-946b3c06-fc9b-413a-82e6-0e58641a543c.png)

Yes, since you are using `opentrons_execute`, you should be using this setting along with the [`labware.set_offset` API](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.labware.Labware.set_offset). Using `opentrons_execute`, you _must_ use `labware.set_offset` in your protocol to use labware offsets.

Please see [this support article](https://support.opentrons.com/s/article/How-to-apply-labware-offset-values-in-Juypter-Notebook-and-opentrons-execute) for more details

**Comment by aperkins19** [comment]
@mcous 

Thanks for getting back to me.

All the best.
