### ISSUE TITLE
bug: the calibration for labware isn't preserved between deck positions and is not passed to the notebooks

### ISSUE THREAD

**Issue by bmyury** [Opentrons/opentrons#11711]
### Overview

We have recently upgraded both firmware and app from 4.5.5 to 6.1.0

We noticed few issues:

1. In 4.5.5  - if the labware is calibrated in the desktop app the calibration is automatically passed to the notebook environment. And if after the calibration -  the labware file is copied to the /labware dir of the Jupyter environment the labware will behave as calibrated in the jupyter. This does not happen  after the most recent firmware/app upgrade. Question - which python command or setting can grab and pass the calibration results to the protocol run in jupyter?
2.  In 4.5.5  - if the labware is calibrated in the desktop app in a given deck position - it will retain calibration in all other deck positions. This does not happen  after most recent firmware/app upgrade. If the labware is moved to a different position it needs to be recalibrated. How can we fix this behaviour.
3. 4.5.5 allowed for A0 positions (we used it as a calibration spot on our custom labware). Recent upgrade canceled that - can you guys please bring it back.

Please help

Yury

### Operating system

Windows

### System and robot setup or anything else?

system 6.1.0

**Comment by mcous** [comment]
That's a big jump! Sorry you missed some of the versions in between; this probably would've felt less drastic.

The short version of this story is that these were all very intentional changes; after a lot of research and testing, we can to the conclusion that measuring one offset for a given labware type and using that offset for all slots across all systems caused far more problems than it solved.

> 1. In 4.5.5 - if the labware is calibrated in the desktop app the calibration is automatically passed to the notebook environment. And if after the calibration - the labware file is copied to the /labware dir of the Jupyter environment the labware will behave as calibrated in the jupyter. This does not happen after the most recent firmware/app upgrade. Question - which python command or setting can grab and pass the calibration results to the protocol run in jupyter?

In Jupyter, you can/should use the new [`Labware.set_offset`](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.labware.Labware.set_offset) method to set the offset vector on each of your labware. You can measure or obtain this offset however you would like; it is simply an `x`, `y`, `z` vector in `mm` to tweak where the robot expects to find the labware.

These two support articles should help if you would like to use the Opentrons App to measure the offset:

1. [How to view labware offset data](https://support.opentrons.com/s/article/How-to-view-labware-offset-data)2. 
2. [How to apply labware offset values in Juypter Notebook and opentrons_execute](https://support.opentrons.com/s/article/How-to-apply-labware-offset-values-in-Juypter-Notebook-and-opentrons-execute)

> 2. In `4.5.5` - if the labware is calibrated in the desktop app in a given deck position - it will retain calibration in all other deck positions. This does not happen after most recent firmware/app upgrade. If the labware is moved to a different position it needs to be recalibrated. How can we fix this behaviour.

As noted, this is an intentional change; after much research, we found that labware offsets are rarely universally applicable to every slot.

Using `Labware.set_offset`, you can choose to apply (or not apply!) offsets in your protocol however you would like.

> 3. `4.5.5` allowed for A0 positions (we used it as a calibration spot on our custom labware). Recent upgrade canceled that - can you guys please bring it back.

We are unlikely to implement this feature in the Labware Position Check in the Opentrons App.

As mentioned, however, since you're working in Jupyter, you can use `Labware.set_offset` however you would like! For example, you could use Jupyter to validate and tweak your offset values for each labware + slot combination.

```python
import opentrons.execute
protocol = opentrons.execute.get_protocol_api('2.13')
protocol.home()

pipette = protocol.load_pipette("p300_single_gen2", mount="right")

// test labware offset using well A0
labware = protocol.load_labware('my_cool_labware', location="1")
labware.set_offset(x=0.1, y=0.2, z=0.3)

pipette.move_to(labware.wells_by_name()["A1"])
```

You could take this even further, and save these offsets to your own offsets file, and then apply them however you see fit in your protocols using `set_offset`.

I hope this is helpful! Let me know if there's anything else I can clarify.
