### ISSUE TITLE
bug: Impossible to use 'dropTip' command with fixedTrash on OT-2 and robot server version 7.1.0

### ISSUE THREAD

**Issue by Xanngo** [Opentrons/opentrons#14590]
### Overview

I am using an OT-2 with robot server version 7.1.0.

Communication is being done via the HTTP API.

My objective is to be able to call the dropTip command to drop the tip on the trash.

Currently is not possible because either:

1. The trash labware is not present, or
2. No labware can be loaded on slotName 12

### Steps to reproduce

My objective is to be able to call the dropTip command to drop the tip on the trash.

AFAIK the command should look like this:

```
POST /runs/{run_id}/commands

Payload:
{
    "data": {
        "commandType": "dropTip",
        "intent": "setup",
        "params": {
            "pipetteId": "pipette-0",
            "labwareId": "fixedTrash",
            "wellName": "A1",
            "wellLocation": {
                "origin": "default",
                "offset": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                }
            },
            "alternateDropLocation": false
        }
    }
}
```

The problem arises because the labwareId "fixedTrash" has not been defined, so this command would fail.

As a solution I could try to load the trash labware.

First I added the trash labware:

```
POST /runs/{run_id}/labware_definitions

Payload:

{
    "data": {
         // redacted. Labware definition taken from GET /runs/{runId}/loaded_labware_definitions of a run created from a protocol
    }
}
```
and then:

```
POST /runs/{run_id}/commands

Payload:
{
    "data": {
        "commandType": "loadLabware",
        "intent": "setup",
        "params": {
            "location": {
                "slotName": "12"
            },
            "loadName": "opentrons_1_trash_1100ml_fixed",
            "namespace": "opentrons",
            "version": "1",
            "labwareId": "fixedTrash",
            "displayName": "Opentrons Fixed Trash",
        }
    }
}
```

The python script I used to test can be provided, if needed.

### Current behavior

Either:
1. The drop of the tip fails because there is no trash labware.
2. Adding the trash labware on slot 12 fails with:

```json
{
   "data":{
      "id":"48960f20-3ae7-490b-9bcc-c57a97cc7b8d",
      "createdAt":"2024-03-04T16:09:49.274078+00:00",
      "commandType":"loadLabware",
      "key":"48960f20-3ae7-490b-9bcc-c57a97cc7b8d",
      "status":"failed",
      "params":{
         "location":{
            "slotName":"12"
         },
         "loadName":"opentrons_1_trash_1100ml_fixed",
         "namespace":"opentrons",
         "version":1,
         "labwareId":"Opentrons Fixed Trash",
         "displayName":"Opentrons Fixed Trash"
      },
      "error":{
         "id":"72a2a798-1f3c-4e04-955d-bb0be7f0795b",
         "createdAt":"2024-03-04T16:09:49.282377+00:00",
         "errorCode":"4000",
         "errorType":"AreaNotInDeckConfigurationError",
         "detail":"12 not provided by deck configuration.",
         "errorInfo":{
            
         },
         "wrappedErrors":[
            
         ]
      },
      "startedAt":"2024-03-04T16:09:49.276319+00:00",
      "completedAt":"2024-03-04T16:09:49.282377+00:00",
      "intent":"setup"
   }
}
```

### Expected behavior

Drop of tip should be possible only using run commands.

### Operating system

Linux

**Comment by sanni-t** [comment]
Thank you for the detailed report @Xanngo! And sorry about the inconvenience. The behavior you are noticing is due to a change in how we handle trash locations in the backend. Here's the full explanation along with the new way to drop tips in the trash-

In 7.1.0, we transitioned the backend to classify trashes (trash bin & waste chute) as their own special type, since they really are different from labware. These trashes are categorized under locations called ‘addressable areas’. These addressable areas are properties of the robot deck itself and are fetched from a robot’s [deck configuration](https://docs.opentrons.com/v2/deck_slots.html#deck-configuration). For an OT-2, the default deck configuration is assumed to consist of 11 regular slots and one fixedTrash area.

In order to move the pipette to this fixedTrash area, we have two commands- `moveToAddresableArea` and `moveToAddressableAreaForDropTip`. They both move the pipette to the specified addressable area except `moveToAddressableAreaForDropTip`  has additional parameters for tip drop action. You can check out both commands in the HTTP API documentation: https://docs.opentrons.com/http/api_reference.html#tag/Run-Management/operation/create_run_command_runs__runId__commands_post

With that, here’s an example request for dropping a tip from 10mm above the OT2 trash center:
```
POST /runs/{run_id}/commands

Payload:
{
    "data": {
        "commandType": "moveToAddressableAreaForDropTip",
        "intent": "setup",
        "params": {
            "pipetteId": "pipette-0",
            "addressableAreaName": "fixedTrash",
            "offset": {
                "x": 0,
                "y": 0,
                "z": 10
            },
            "alternateDropLocation": false
        }
    }
}
```

Let us know if this solves the issue you are having, or if you have further questions.

**Comment by Xanngo** [comment]
Thank you @sanni-t !! Very clear, it seems to be working as expected :)

I'll do some more tests and get back to you

**Comment by SyntaxColoring** [comment]
> In a future update, would it be possible for the drop tip command to take an addressable area as a value in the location parameter?

Potentially. So far, we've been deliberately avoiding that in favor of having commands that do one thing at a time. Like `moveToWell` followed by `aspirateInPlace`, instead of just an `aspirate` that moves *and* aspirates. Basically for simplicity and composability.

Admittedly, this gets ugly when the details of the movement depend on *why* you're moving there. Here, we ended up with a `moveToAddressableAreaForDropTip` that's separate from `moveToAddressableArea` so it could have the extra `alternateDropLocation` parameter.

**Comment by sanni-t** [comment]
^That made me realize, @Xanngo, I forgot to mention that in order to actually drop the tip, you will have to use a `dropTipInPlace` command after moving to the trash. You probably figured it out already since you got it to work, but just want to mention that missing piece.
