### ISSUE TITLE
Show pipette moving + spinner overlay on deck calibration exit

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1613]
## overview

When exiting deck calibration: it doesn’t have the same pipette moving + spinner overlay as when you start calibration. Because the exit modal just persisted after clicking exit I wasn’t sure if that was going right. 

## steps to reproduce

- [ ] Start deck calibration 
- [ ] Exit deck calibration

**Comment by mcous** [comment]
Reclassified as a feature because:

- App was implemented as spec'd by screens
- Robot responds immediately with a success message to a restart request, meaning tracking robot restart state in the app is too difficult

@pantslakz could you add one more screen to the Deck Calibration Zeplin project for spinner copy during restart?

@btmorr I think we need to discuss the `/restart` endpoint a little bit to figure out the best path for both displaying the fact that the robot is about to go / currently going down, and how to track when the robot comes back up properly.

**Comment by mcous** [comment]
I think I misunderstood this ticket; this seems to be about early exit from deck calibration. Reclassified ticket back to an app bug accordingly.
