### ISSUE TITLE
Linux app package has invalid name starting with non alphanumeric character

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#1619]
## overview

Downloading the .deb file from Wikidot and installing it with `apt install` results in an error stating the package cannot be installed because it does not start with an alphanumeric character. It appears to start with `@` for some reason.

## behavior

`apt install` fails installation with this error:

    dpkg: error processing archive /path/to/pkg/Opentrons-v3.0.0-beta.9-linux-b7748.deb (-- 
    unpack):
    parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
    invalid package name (must start with an alphanumeric character)

and the package name appears to be `@opentrons/app-shell`

## steps to reproduce
OS: Ubuntu 18.04
Version: App version appears to be 3.0.0-beta.9 (the latest hosted on Wikidot)

Download the package with:

    wget https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.0.0-beta.9-linux-b7748.deb

Try to run `dpkg` or `apt install` on the file. Should fail with invalid package name.

**Comment by mcous** [comment]
Thanks for the ticket! This issue was resolved with #1557 and released with version 3.1.1.

I've been informed by our support team that the Wikidot page has been deprecated as all information has been moved to our support site. You should see an email about it shortly and the Wikidot site will be taken down. Thanks for bringing this to our attention!

- Download links: http://opentrons.com/ot-app
- Latest `deb` release (`v3.1.2`): https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.1.2-linux-b8990.deb
- Support site: https://support.opentrons.com/
