### ISSUE TITLE
WIP - CSS Cleanup: ".button_row"

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#1670]
`.button_row` class appears across:

- Form.css (also has `.simple_button_row`)
- MoreOptionsModal.css
- StepEditForm.css
- IngredientPropertiesForm.css (where it is flex)

`IngredientPropertiesForm.css` uses flex and the others use `lost-grid`

Does Run App also have a few different ways to set up buttons in a row with different widths & offsets as well? (I half-remember talking about this)

Should a grid system manage this?

**Comment by Kadee80** [comment]
The only time we have buttons in a row (besides in alert modals - which have a set width and usually live in a flex container) is jog controls. Because they are generated from props and are very position specific, I used CSS grid, rows, cols, and spans. 
https://github.com/Opentrons/opentrons/blob/edge/app/src/components/JogControls/styles.css#L8
Thats a one off. We dont have many buttons
