### ISSUE TITLE
Protocol prompts pause until user hits 'Resume'

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1694]
As a user, I would like to include a pause command in my protocol, which continues only when I hit "resume" in Run App.

## Acceptance Criteria
- User able to pause a run from within protocol
- sees pause in RUN LOG with some kind of custom message (ie. "Add re-agent to well 4 and then hit resume") either in RUN LOG or Pause Banner
- User hits "resume" button in Run App

**Comment by mcous** [comment]
@pantslakz to clarify, "User able to pause a run from within protocol" and "User hits 'resume' button in Run App" acceptance criteria already work with existing protocols. So that means this ticket is specifically for showing a more detailed message in the run log or in a banner, correct?

**Comment by pantslakz** [comment]
@mcous yes!  @IanLondon can provide more detail relating to Protocol Designer.

**Comment by mcous** [comment]
Is this a Protocol Designer ticket or a Python protocol ticket or both?

**Comment by IanLondon** [comment]
@mcous 

It's a Python API ticket - I propose `robot.pause` command should take a `message` param (right now it's no params) which gets put into the `payload = {'text': message or 'Pausing robot operation'}` of `make_command`... or something like that. And in the JSON protocol executor, it will call robot.pause with the appropriate message. 

By changing `robot.pause` to take an optional message instead of doing something only in the JSON protocol executor, Python protocols can also take advantage of this "show me a message during the pause in the Run commands list" behavior.
