### ISSUE TITLE
Pipette Not Recognized

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1968]
## Expected Behavior
- Pipette name should appear in Run App when properly plugged in

## Observed Behavior
- Run App reports that pipette is not recognized

## Steps to Recreate
- TBD

**Comment by umbhau** [comment]
@mcous @pantslakz 

FYI -- recreated this bug b/c the issue reemerged on one of @pantslakz customer calls yesterday.

**Comment by mcous** [comment]
@umbhau and @pantslakz this ticket needs more information. On what screen does the app "not recognize" the pipette? What version of the app has this issue?

If the answers to those questions are "Calibrate > Pipette Calibration" and `v3.2.0`, then this issue was fixed for most cases by #1830 (released in `v3.3.0-beta.0`) and fully fixed by #1895 (released in `v3.3.0-beta.1`)

**Comment by pantslakz** [comment]
Confirming that answer is Calibrate > Pipette Calibration" and v3.2.0,

**Comment by umbhau** [comment]
@mcous @pantslakz Any objections to my closing this one?

As far as I know we had three different issues, all of which are now resolved:
1) Bug in FW version 3.1.2
2) Bug in Run App version 3.2.0 (calibrate -> calibrate pipettes)
3) Pipettes not flashed

**Comment by umbhau** [comment]
Closing this issue -- believe all known root causes are fixed.
