### ISSUE TITLE
Protocol Delay Working Like a Pause

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2031]
Protocol delay currently being represented as a protocol pause in the run app.

## Expected Behavior
- During a protocol delay (pipette.delay(time)), user should see an alert bar 
- Alert bar should say 'Delaying for X time'
- Run clock should continue incrementing during delay
- User should not be able to resume protocol

## Current Behavior
- Robot displays a 'pause' alert bar
- Run clock stops incrementing
- User able to resume protocol

## Steps to Recreate
- Load and run a protocol with the following command: p300.delay(minutes=3)
- Observe robot pause during delay

**Comment by Laura-Danielle** [comment]
Has this been fixed yet? @umbhau @sfoster1

**Comment by mcous** [comment]
Upon investigation and some timeboxed experimentation, I'm ice-boxing this feature request until RPC is replaced. Delay working via `pause` and `resume` was an intentional API decision, and unwinding that to implement these features as requested exposes too many technical and UX edge cases.

Rather than risk implementing something buggy (or introducing new bugs in existing behavior), we'll keep this ticket in mind as table-stakes for the new Sessions API

**Comment by Matt-Zwimpfer** [comment]
Fixed in Protocol Engine
