### ISSUE TITLE
RPC: WebSocket connection should be monitored with a ping/pong

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2052]
## overview

When the robot has been idle for some amount of hours, and you try to load a protocol, you get an ACK timeout error. As a user, this doesn't give me any indication as to what went wrong or how to fix it.

## current behavior

ACK timeout after robot has been idle for too long when trying to upload a protocol. Disconnecting and reconnecting the robot fixes the issue.

## steps to reproduce
App version `3.2.0`
robot server `3.2.0`

Let the app and the robot idle for a few hours, then try to upload a protocol.

## expected behavior

Should upload the protocol regardless of ACK timeout. If ACK timeout occurs, refresh the connection automatically and try again. At the bare minimum, a helpful error message should tell me how to fix it.

**Comment by mcous** [comment]
Seems like the RPC WebSocket is half-closing or something. With a simple ping-pong processes running on the socket at all times we could detect a bad socket early and close it manually (as a precursor to implementing auto-reconnect attempts).

Ping @btmorr and @b-cooper because we've talk about this in the past
