### ISSUE TITLE
Possible memory leak warning

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2105]
## overview

Toggling Developer tools on and off in the same session emits the following warnings multiple times:

    (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
    (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
    (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit

Could this potentially be a cause of #2042 ?

## steps to reproduce

Robot server 3.2.0
App version 3.2.0 for Linux

Open app, turn developer tools on and off repeatedly. Observe output in the console.

**Comment by mcous** [comment]
The apps' developer tools only print logs related to the app. Given that...

- This is probably not actually a memory leak (see below)
- If it is a memory leak, it's a memory leak in the app
- During a protocol run, the app passively listens to the robot; it has nothing to do with actually executing the run outside of the "Start", "Pause", and "Cancel" buttons

...this warning printout definitely has nothing to do with #2042 

---

**Why this warning gets printed**
 
Node.js's [built-in EventEmitter](https://nodejs.org/api/events.html#events_events) class has a listener limit (i.e. number of times another piece of code requests to be notified of a given event) that, if exceeded, will cause Node to print out that advisory. It's important to note that the limit itself is completely arbitrary and, in well-behaved users of the EventEmitter class, set by the that user. It's also important to note that the only thing that happens when that limit is exceeded is that the warning is printed. Exceeding the arbitrary limit does not change anything about the behavior of EventEmitter and is not necessarily an indication of a bug.

This warning is _probably_ (I say probably because I'm unable to reproduce this behavior) being emitted by a library we use that doesn't set this warning limit properly.
