### ISSUE TITLE
Protocol Info

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2129]
As a Run App user, I would like to be able to see basic info about my protocol when I upload it to the Run App, so that I know what to expect from the run.

## Acceptance Criteria
- User sees protocol info
-- Protocol Name
-- Protocol Author
-- Protocol Last Modified Date and Timestamp (28 Aug 2018, HH:MM)
-- Protocol Type ('Python'/'JSON')
- User sees list of pipettes required for protocol
- User sees list of modules required for protocol
- User sees list of labware (and quantity of each) required for protocol

## Design

- https://zpl.io/adkX0D7
- https://zpl.io/29yKege
- https://zpl.io/V4l57y8
- https://zpl.io/am4M0K3
- https://zpl.io/a7Ed8zp 
- Keep existing upload in progress screen
- Keep existing upload error screen

**Comment by pantslakz** [comment]
Designs for review:

Zeplin > Run App Screens > Tagged "File Info"

**Comment by howisthisnamenottakenyet** [comment]
@umbhau @pantslakz  I'm not sure what the user would get out of having the protocol type there. However we should be displaying PD version it was made with if it's a JSON file.

**Comment by pantslakz** [comment]
I think for us it may seem obvious if something is python or Json, but there could be cases where users have the extension turned off on their OS file options, and unsure of what the file type is? 
also I added it for consistency between file types

**Comment by pantslakz** [comment]
@Kadee80 @mcous please note we'll need to add "modules" to this popup:

![screen shot 2018-09-05 at 12 03 09 pm](https://user-images.githubusercontent.com/2686086/45086508-905f8f00-b103-11e8-8325-10ffe5047974.png)

**Comment by mcous** [comment]
@pantslakz even if the user has their "display extensions" option turned off, the files themselves still have extensions. We'll be operating on the technical assumption that if a file has a `.json` extension, then it is a PD protocol, and if it's anything else, we'll try to upload it as a Python protocol (I've seen support cases where users save their Python protocols as `.txt` instead of `.py`).

A message somewhere communicating this logic to the user might be helpful; maybe it would make sense to put it in the failed protocol parse/upload screen
