### ISSUE TITLE
Using move_to commands does not cause container to appear in calibration

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2257]
## overview

Using the `move_to` method does not cause its target to show up in the calibrations. Protocols without aspirate and dispense commands do not add all containers to the labware calibration.

## current behavior

Say we want to exclusively access a piece of labware exclusively by `move_to`. Currently the labware is not added to the calibration screen unless come liquid transfer occurs on it. `move_to` will not trigger the labware to appear on the calibration page.

## steps to reproduce

App/Robot server  `v3.2.0`

 Assume we have a `P10_Single` defined with tips, a 96-well plate, and a custom container.  A protocol with the following commands will only send the tip racks to the calibration screen:
    
    p10.pick_up_tip()
    p10.move_to(custom['A1'])
    p10.move_to(plate['A1'])
    p10.drop_tip()

Adding a transfer command to the bottom (even at zero volume) causes the containers to be added to the calibration:

    p10.pick_up_tip()
    p10.move_to(custom'A1'])
    p10.move_to(plate['A1'])
    p10.drop_tip()
    p10.transfer(0, custom['A1'], plate['A1'])

## expected behavior

Actual liquid handling should not be required to calibrate a container. The container should be added to the calibration even if it is only accessed by `move_to`

**Comment by mcous** [comment]
Closing as a duplicate of #234, and sorry this ticket has been sitting here without a response for so long.

This is a known behavior due to how the robot's software determines whether a piece of labware is "used" or not. It's a relic of an earlier time where this behavior was viewed by the dev team as a feature rather than the completely unexpected behavior that it is.

The fix for this has been a _very_ long time coming but we are, in fact, actively working on it
