### ISSUE TITLE
Run App shows incorrect "suggested tip type" during calibration > tip probe

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#2444]
As a Run App user, I would like to be instructed to use the same tip for tip probe and protocol run.

## Acceptance Criteria
-  Before tip probe, user is told to add a tip to their pipette
- Tip type should be the same as whatever they're using in the protocol _on that pipette_

## Copy 
- TBD

## Implementation Notes
- Note tip length is currently a property of the pipette (will eventually be a property of tip rack)

**Comment by mcous** [comment]
> Note tip length is currently a property of the pipette (will eventually be a property of tip rack)

I don't think tip length enters into this, because the API separates that information from tip type. (In fact, if I understand the state of things correctly, the API doesn't really have a concept of tip types at all).

What we do have, however, is a list of one or more tiprack types that the user has indicated they will use with a given pipette in the protocol:

```py
rack1 = labware.load('opentrons-tiprack-300ul', '1')
rack2 = labware.load('opentrons-tiprack-300ul', '2')
p300 = instruments.P300_Single(mount="left", tip_racks=[rack1, rack2])
```

So, questions for @pantslakz and @umbhau:

1. Is it acceptable to _try_ to parse the tip type from the labware type
    - From the name because, as mentioned above, the API doesn't really have a concept of tips
    - If we parse from type, we need to deal with the possibility that we are unable to parse a type
2. If the user attaches more than one tiprack to a pipette, which one do we select for (1)?

Ping @btmorr in case I'm missing something about how pipettes and labware are currently working.
