### ISSUE TITLE
Install the App for all users

### ISSUE THREAD

**Issue by cmfield** [Opentrons/opentrons#2567]
Is it possible to install the App on Windows for all users of the computer?

**Comment by mcous** [comment]
Hi @cmfield, thanks for the request! By default, the app is configured to both:

1. Not require an install wizard (i.e. use a one-click installer)
2. Install the app per-user (instead of per-machine)

Per-machine isn't an option for our users in environments where they don't have IT permission to install applications system-wide, so if we allowed (2) to be configurable we'd also have to switch (1) from a one-click installer to an installation wizard.

I'll ask our UX team about this, but in the mean time: for you personally, would the annoyance of having to click more buttons to install the app be worth it to gain the ability to install per-machine?

**Comment by mcous** [comment]
Unfortunately it's a [build time configuration](https://www.electron.build/configuration/nsis) for us, so we'd have to change it for all Windows users. We'll run through it on our end and see what it looks like; given this is something you need we'll likely end up enabling configuration in the wizard. I'll keep this thread updated
