### ISSUE TITLE
Warning when user clicks create new protocol if a protocol is open

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2756]
As a user I don't want to accidentally delete my protocol

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535388481) by [Unito](https://www.unito.io/learn-more)

**Comment by pantslakz** [comment]
Feedback from user:
"I started a second protocol without saving/running the first. I didn't know that I could only create one. When I started I was served this message: "Are you sure you want to create a new file? Any unsaved changes will be discarded."  As a user I'd prefer more of an explanation and an earlier warning i.e. serve me the message when I click 'create new' instead of after I begin creating the second version."
