### ISSUE TITLE
NotImplementedError [line unknown]: Need to implement new api in protocols

### ISSUE THREAD

**Issue by wvconnors** [Opentrons/opentrons#2842]
## overview

Hi, couldn't find any existing support information so I'm submitting this as a new bug -- no matter the most basic of protocols (anything that calls pipette.transfer(), .aspirate(),  .dispense()....) I'm getting the above error thrown when opened in the opentrons app, with the message 'Your protocol could not be opened.' Not having a lot of luck debugging via jupyter notebook, but I can confirm I get a similar NotImplemented error for pipette.dispense. This is true for protocols such as the exact one below, variations, ones downloaded from the protocol library website, and ones designed and exported using Protocol Designer. 

## steps to reproduce
`from opentrons import labware, instruments
plate = labware.load('generic_96_wellPlate_380_uL', '2')
tiprack = labware.load('opentrons_96_tiprack_10_uL', '1')
pipette = instruments.P50_Multi(mount='right', tip_racks=[tiprack])
pipette.transfer(5, plate.wells('A1'), plate.wells('B2'))`

robot and app version 3.6.5
option 'Use Protocol API version 2' set to ON
upload test.py to app

**Comment by mcous** [comment]
Hi @wvconnors, please turn "Use Protocol API version 2" should be set to off. There was a bug in `3.6.1` that was fixed in `3.6.2` (and subsequent releases) that could cause the value of that setting to switch. As described on the advanced settings page:

> *Use Protocol API version 2*
>
> Use new implementation of protocol API. This should not be activated except by developers.

The "Not Implemented Errors" are because we have not implemented simulate/run support in the next-gen protocol API
