### ISSUE TITLE
API: pause at end of protocol causes stall

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3238]
## steps to reproduce

- Make a protocol that contains `context.pause` as the LAST step in the protocol (for example, a JSON protocol that ends with an indefinite `"wait": true` "delay" command)
- Run protocol in Run App
- When this pause command comes up, "Reset Run" appears in Run App instead of "Resume"
- Clicking "Reset Run" makes the robot unresponsive to Run App (permanent spinner on run/home/upload/calibrate)

## expected behavior

It might be desirable to pause as the last step when you don't want the robot to home right away, to keep the pipette in position until you're ready.

## Tech notes

@btmorr says: the likely cause is that the pause doesn't stop the protocol from ending, the `context` object gets garbage collected and the pause can not be resumed

**Comment by sfoster1** [comment]
This isn't actually apiv2 specific. This is specific to how pause is kind of a hack that pokes at low level smoothe interactions.

When you pause, you set a threading flag in the smoothie driver. `home` and `move` wait for that flag to set before executing. So, in the normal course of events, you call pause, and then _the next time one of those is calls_ they'll wait until resumed, presumably by the runapp or some other client.

So when a pause is the last action in a protocol.... it doesn't pause because there is no next command to pause. But the flag is still set! So going forward, motion commands won't execute. So it all locks up when it does the home after the protocol ends.

In the long term, we should fix this by making pause not work like this (and in fact we're going to). In the short term, we can fix the lockup by always calling resume when a protocol ends, but it's harder to fix the protocol ending nicely.
