### ISSUE TITLE
Can't find OT2 device via USB, except disable local PC's network card

### ISSUE THREAD

**Issue by simonchih** [Opentrons/opentrons#3243]
## overview
With Opentrons app version 3.7.0. It can't find OT2 device via USB.

## current behavior
Can't find OT2 device via USB with Opentrons App.

## steps to reproduce
1. Local PC's network card is enable.
2. Power ON OT2
3. Connect PC and OT2 via USB line.
4. Open Opentrons App in local PC.
==> Can't find OT2 device via USB and network status is unidentified network.

Note: Opentons App can find OT2 device if disable local PC's network card.

## expected behavior
Opentrons App can find OT2 device via USB.

**Comment by mcous** [comment]
Hi @simonchih, from the description of your symptoms, this sounds like a problem with your computer's networking / routing setup. I recommend reviewing our [networking requirements support document](https://support.opentrons.com/guide-for-getting-started-with-the-ot-2/3-set-up-the-ot-2-app/c-network-requirements-for-the-ot-2).

If you're still having issues, please reach out to our support team at <https://support.opentrons.com> or via in-app chat. I'm going to close this ticket because it is best handled by our support team, but I will re-open if we end up uncovering a bug or potential improvement to make!
