### ISSUE TITLE
V2 Labware: Get Labware Definitions Locally

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3334]
As an Opentrons user, I would like to use getLabwareDef to retrieve JSON labware from redux (instead of using getLabware to get defs from shared data)

## Acceptance Criteria
- [ ] All instances of getLabware functions should be replaced with getLabwareDef
- [ ] Ever place where getLabware is called should now expect a V2 labware in the response

## Implementation Notes
  - getLabware takes a load name and returns a definition from shared data
  - getLabwareDef takes an OT ID and returns a definition from local redux state
  - add a short term shim that allows getLabwareDef to map a load name to an OT ID.

**Comment by IanLondon** [comment]
Most of the work in this ticket has been done.

Remaining uses of `getLabware` fn:
- protocol-designer/src/load-file/migration/1_1_0.js for getting v1 tiprack definition in PD migration (which seems like an OK use to me)
- indirectly thru complib `Labware` component import, this will be removed in #3532

Remaining work to close this ticket:
- rename `getLabware` to `getV1LabwareDef`
- have `getIsTiprackDeprecated` and `getWellDefsForSVG` take a V1 labware def object instead of a string, and rename them to reflect that they are intended for v1 labware defs

Then, the v1 -> v2 shim will finally be removed once migration is implemented, outside the scope of this ticket (see #3337)
