### ISSUE TITLE
Apiv2 Last Mile: Well-defined entrypoint for jupyter

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3546]
Add an entrypoint usable from Jupyter (or interactive python shell) for running a protocol. There should be one for both protocol apis 1 and 2.

This should probably take the form of something that returns an instantiated protocol context that can have methods called on it. It should connect to the hardware controller using #3545 .

**Comment by Laura-Danielle** [comment]
Proposal
---------

Since we are forgoing access to the hardware controller via a jsonrpc client/server for now, we can simply use a normal entrypoint input.

1. All tools requiring entrypoints (deck calibration/commandline, simulation, jupyter) will utilize a shared protocol context function.
2. For interactive protocols (i.e. python shell and jupyter notebook) there will be a protocol context for both simulation and connecting to the actual hardware.
3. For non-interactive protocols (i.e running a protocol from the commandline) we will simply utilize a fully connected protocol context.
4. When it's time for backcompat, calls to instrument/labware will always be the simulation context _until_ someone runs `robot.connect()` and then it will be a regular `ProtocolContext`.

Now that locking is removed as of #3962, we don't have to worry about strictly managing protocol contexts like before.

Jupyter Notebook Future
-------------------------
If we decide that we want to build out the features of jupyter notebook, we could try to implement https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

This way users wouldn't need to explicitly specify a simulating context and a protocol context. They could instead switch between the two with some type of GUI shown in the README above.

Notes
------
Since interactive protocols will not be utilizing a `run` method, we'll need to make sure we are very explicit about the differences in the docs.
