### ISSUE TITLE
Protocol run: pause run and prompt for user input

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/opentrons#356]
It would be great to be able in the user interface to prompt for user intervention - e.g.

```
import time
def safeGet200Tips():
    global TimesTipsLoaded
    if TimesTipsLoaded == 12:
        time.sleep(20) #This could be user_intervention("Load tips")
        p200x8.reset_tip_tracking()
        TimesTipsLoaded=0
    p200x8.pick_up_tip()
    TimesTipsLoaded=TimesTipsLoaded+1
```

In simulating the code the app would just need to dismiss these prompts.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535406983) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
As of `v3.4.0`, `robot.pause` now takes an optional `msg` parameter that will display in the run log of the app...

```py
robot.pause(msg='Pausing; please load tips')
```

...which will wait for the user to click "Resume". @theosanderson is the kind of functionality you were requesting?

(Although, while #2047 is still a thing, a pause message in the run log is of limited usefulness if it isn't correctly highlighted)

**Comment by theosanderson** [comment]
Perfect - thank you.

**Comment by b-cooper** [comment]
Just closing the loop on this now. Apologies for the delay in communication.

This was great feedback and we were able to incorporate it directly into the 6.3 release last summer.  Since then, `pause()` calls from the python api and any `waitForResume` protocol engine command will present a dialog box "front and center" along with the message that was passed as a parameter to the call. This experience is the same on OT-2 and Flex robots.  The latter will also provide a similar dialog on its embedded touchscreen display to catch the operator's attention.

<img width="687" alt="Screen Shot 2024-03-18 at 2 03 31 PM" src="https://github.com/Opentrons/opentrons/assets/4731953/5db0b423-f284-4fbb-9870-d5252f5746b8">
