### ISSUE TITLE
Thermocycler: Update Firmware First Pass

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3580]
As a TC user, I would like to be able to update my Thermocycler's Firmware from the Run App.

## Acceptance Criteria
- [ ] User able to initiate firmware update from the module card in the Run App
- [ ] User able to select firmware file from dialogue
- [ ] User informed when firmware update is complete

## Implementation Notes
- Follow design and system patterns from Tempdeck update. Second pass will be covered by larger module firmware update experience in #1736

**Comment by b-cooper** [comment]
The module firmware update pathway has been rethought such that most of the responsibility for orchestrating the correct update occurs on the robot software level, not the user level. Instead of POST'ing module firmware to the robot from a run app file select, we'd like to include the most recent module firmware in the filesystem of the robot's operating system at build time. Much like https://github.com/Opentrons/buildroot/pull/57 does for the smoothie firmware.
