### ISSUE TITLE
FE Monorepo Projects: Centralize links

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4229]
## overview

It would be nice to centralize our link component(s) and to also centralize the data of our link URLs.

LL uses a `LinkOut` component, there's also PD's `KnowledgeBaseLink`.

URLs are kept in various constants etc, maybe we can put them all in a `getUrlLink` fn in shared-data that we use across FE monorepo projects for absolute URLs?

**Comment by Kadee80** [comment]
I like this idea, RA has links in the 'More' section and could potentially have them in some of the alerts. Happy to help with an audit of all things `href` in the monorepo.

One thought, I don't think `LinkOut` in complib should have any styling assigned since overwriting styles has become cumbersome.
