### ISSUE TITLE
Protocol Designer: Blowout Destinations faulty options

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#4348]
## overview

When choosing a blowout destination,  I am given the option to select a well plate and even a tiprack instead of choosing traditional blowout destinations; "trash", "source well", or "destination well" .

![Screen Shot 2019-10-31 at 11 29 32 AM](https://user-images.githubusercontent.com/4731953/67962522-9a7c0100-fbd3-11e9-8137-6a7e43df3dbb.png)

## current behavior

displayed options present tip racks and other labware as viable blowout destinations.

## steps to reproduce

Select blowout advanced option in a transfer step.

## expected behavior

Should only see the following options "Trash", "Source Well", "Destination Well".

**Comment by shlokamin** [comment]
as per discussion with @b-cooper :

In saying “Trash, Source Well, and Destination Well are the only options…“, what I really meant to say is, “Trash, Source Well, and Destination Well are the only possible options, with each combination of stepType and path corresponding to a subset of those three”

The reason why that helper util exists over a hard coded list is that we only know which of the three options to display in any blowout dropdown if we know the stepType (e.g. ‘mix’, ‘moveLiquid’, ‘pause’) and the path (e.g. ‘single’, ‘multiAspirate’, ‘multiDispense’).

For example, If a user encounters a blowout dropdown on a “moveLiquid” step and they have selected “multiDispense” as their path option. They should no longer be able to select “Destination Well” from the dropdown, as “Destination Well” is ambiguous when there are more destination wells compared to source wells. We also couldn’t assume they want to blowout in the last destination well for every set, because this may lead to non uniform destination well volumes.
