### ISSUE TITLE
Build: Support building Python projects without JS dev dependencies

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4760]
As a mostly Python developer, I'd like to be able to contribute to the pure Python projects without having to learn about tools like `nvm` and without having to set up a JavaScript development environment.

`shx` is used throughout the build system for cross-platform POSIX commands. But pulling in a JavaScript engine to run `cd` tastes kind of sour to me.

We already depend on GNU Make. Could we not just depend on GNU Coreutils, as well?

**Comment by mcous** [comment]
From what I can tell, installing GNU Coreutils to work in regular cmd + powershell looks like a pain due to PATH management and the fact that POSIX command overlap with Windows commands (e.g. `rm`). But yeah, I'm sure there's a path forward for this.

`shx` has two benefits that we take advantage of and should consider when trying to replace:

- Handles globstars, which otherwise would depend on each person's shell setup
- (As pointed out in the OP) Works cross platform

We use `shx` for the following commands:

- `rm -rf` (prior to `shx`, at least one OT engineer on Windows wiped out a large portion of their filesystem because Windows `RM` is drastically different than POSIX)
- `mkdir -p`
- `ls`
- `find`
- `cp`

We rely (off the top of my head) on the following built in stuff being consistent across platform:

- `cd` (works pretty much the same in all shells)
- `&&` (both Windows and POSIX shells support command chaining via `&&`)
