### ISSUE TITLE
Modifying my local copy of the opentrons library fails to make any difference in the robots behavior

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#539]
## overview

Version: 2.5.2
OS: Windows 7 Enterprise

I would like to by default set the `home_after`  keyword in `Pipette.drop_tip()` to `False` because it improves protocol speed by around 30-50% on protocols that use a lot of tips. This option is not publicly exposed, but I found it in the `opentrons` library in `pipette.py`->`Pipette._drop_tip_during_transfer()` method and set this option to `False` during transfer commands. Changing this option had no effect on the robots behavior and it continues to home the plunger axis after changing the code. I've changed my import path at the beginning of the script to import third party libraries and I import `opentrons` from the same location. The lack of a change in the robot's behavior combined with the unclear Python environment used by the App makes me think that the app is using some alternate python installation and environment. It's not the default python.exe installed by my computer because any libraries imported in python scripts need no path manipulation when run from the command line.

## behavior

Expected:
- I make a change in my local copy of the opentrons library and have that change implemented by the robot.

Actual:
- the default opentrons library is imported instead of my modified version

## suggestion

-  Clarify the Python environment used by the opentrons app. Expose and document the `home_after` option so I can improve protocol speed by 50% with a single boolean argument. If the plunger axis falls out of calibration every single tip then this is a much larger hardware issue, otherwise having this command set to `True` by default slows down protocols from "usable" speed to "I'm staying an extra 2 hours at work so the robot can home its plunger axis on every single transfer" speed.

**Comment by mcous** [comment]
Thanks for filing this issue! I just spent a little bit of time discussing this with my colleagues, and hopefully I'll be able to clear things up. My answers will be in the context of the OT-2 and the re-written app, as that is where all our development effort is focused at the moment.

## python environment

Things changed a lot here between the OT-1 and OT-2 in this regard. With the OT-1, the app launched a Python child process that ran the API software. With the OT-2, the robot has an onboard Linux computer that runs Python 3.6.

### updating the code on your robot

If you would like to run custom code on your robot, first set up a development environment as described in our [Contributing Guide](https://github.com/Opentrons/opentrons/blob/edge/CONTRIBUTING.md#development-setup). If you're using Windows, I recommend using [the Chocolatey package manager](https://chocolatey.org/) to install the required tools.

Once you have your environment set up, you can push custom code to you're robot with:

(Please excuse my Unix path separators. This will work on Windows, too)

```shell
# change into api directory of the repository
cd path/to/opentrons/api

# push to a robot connected by its USB cable (USB-to-ethernet adapter)
make push
make restart

# alternatively, push to a robot on the network (example IP 1.2.3.4)
make push host=1.2.3.4
make restart host=1.2.3.4
```

## home_after=True

After consulting with the API team, the consensus is that homing the plunger motor after a drop tip is required, because the plunger motor is also what pushed the tip off. We intentionally over-drive the motors slightly during tip pickup to ensure a tight seal. Accordingly, the act of pushing the tip off may cause the stepper to miss steps as it pushes the tip off, so the home is necessary. The `home_after` parameter was likely left undocumented because it was not meant to be used publicly.

The overall improvement in speed available with the OT-2 should (hopefully) address the concerns that led you to seek out the parameter in the first place.

I'm going to close this ticket out, but I'm happy to post additional details / re-open as necessary if you have any more feedback!
