### ISSUE TITLE
Feature Request: Two-point calibration

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#542]
## overview

Currently the tip boxes are calibrated using a single point. Then the robot is essentially assuming the location of all tips based on the location of the first. This is unacceptable given the degree of "jiggle" movement in the slots and the uneven plane of the base plate. The slots aren't at all uniform and are sloped in random directions. A two-point calibration of containers allows the exact position of every tip or well to be mapped in 3 dimensions. No assumptions need to be made about their locations and it's worth an extra calibration per container to ensure this. Every major automation platform uses this strategy and struggling with the OT-One has made me realize that this is an absolutely essential part of calibration.

Just now the robot started missing tips on the last 30 transfers out of 300 unique transfer volumes and reagents. The reason we use this robot is for a mistake free pick-and-place of primers or samples or whatever. First of all, when I know this behavior exists, it forces me to watch the entire 3 hour protocol (could be 2 hours, see Issue #539) to make sure it pipettes everything without missing, and it's also extremely difficult to finish the protocol by hand when the robot messes up, which by now I'm realizing is nearly every single run. I just had to throw out 32 PCRs because the robot started missing tips randomly. We mounted Rainin pipettes on the robot because the DragonLab ones would crash tips towards the end of the box as a result of the same issue.

Frequently, the robot will start missing tips towards the back of the box (or crashing) because the tips are on a different Z level. The only "solution" I have found is to jam the pipette too hard into the first tip during calibration to ensure it will be able to pick up the rest of them. It obviously doesn't work very well.

I've been trying to get this robot to function reliably for months, and the only protocol it can execute with any degree of consistency is a 24 sample dilution. PCR assembly and DNA quantification (bread and butter protocols of molecular biology) are off the table due to the number of transfers (anything over 50 tips starts to get risky), and the hardware limitations from the poorly configured pipettes and slots.

I know this issue board is not the right place to voice this , but I have had no luck trying elsewhere. At this point I would say the OT-One is absolutely unusable. I've heard many of these serious issues will be solved in the OT-Two, and all I can ask is that a two-point calibration is optional.

Thank you,

Ryan
  

## behavior

Robot can't hit every tip in the box consistently.

## steps to reproduce

Just try to use an entire box of tips multiple times. Crash/miss becomes highly likely the further away it gets from the calibration tip.

**Comment by mcous** [comment]
I'm really sorry to hear that your experience with the OT-1 did not live up to your expectations, and thanks for taking the time to post this. We've been hard at work improving both the hardware reliability and the calibration experience with the OT-2 compared to the OT-1.

I'm closing this issue because the improved mechanical reliability of the OT-2 hardware along with the corrected labware definitions we've been working on in software should take care of this sort of drift, so we do not plan on implementing two-point calibration for the OT-2 at this time. This could change in the future, though, and if it does we'll update this thread accordingly.

Unfortunately, we don't have the engineering resources available to backport this sort of feature to the OT-1. That being said, if anyone from our community would like to make updates to the legacy app, we're happy to re-open tickets and help out. The legacy version of the app lives in the `ot1-stable` branch of this repository.
