### ISSUE TITLE
bug: App occasionally shows Wi-Fi connected ghost robots that don't actually exist on the network

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5462]
# Overview

The Opentrons App is occasionally haunted by ghost robots.

# Current behavior

When I took this screenshot, I was connected to S1-R10 over USB. S1-R1 is a robot on a completely different network; I'm quite certain my computer couldn't possibly have heard anything from it.

<img width="359" alt="Screen Shot 2020-04-21 at 4 18 28 PM" src="https://user-images.githubusercontent.com/3236864/79924384-85e32d80-83ec-11ea-991d-b6c2e29bd7e9.png">

If I click **S1-R1**, I see this:

<img width="672" alt="Screen Shot 2020-04-21 at 4 18 43 PM" src="https://user-images.githubusercontent.com/3236864/79924397-8b407800-83ec-11ea-8415-5c30e58e6ec2.png">

Unfortunately, neither **error.log** nor **combined.log** contain any recent mention of S1-R1.

The ghost robot persists for a while, but it does eventually disappear from the list.

# Steps to reproduce

This seems to happen randomly. It's not clear what causes it.

When I've noticed it happen, I've been connected to a different robot over USB.

I had been connected to the ghost robot over Wi-Fi before, along with several other robots all sharing a WLAN. That WLAN is isolated, so I'm sure my computer isn't seeing its traffic.

**Comment by mcous** [comment]
Presumed fixed by https://github.com/Opentrons/opentrons/pull/6193. Two properties of the discovery client in versions prior to 3.20 would allow this to happen:

- All state is tracked per IP address, which could have allowed stale data from `S1-R1` to sneak in if it had ever used the same IP address as `S1-R10`
- The inherently faulty "your robot is advertising its IP address" logic was removed in favor of simpler logic that:
    - Tracks if a given IP address has been seen in any way (mDNS or health polling) while the app has been open
    - Notes whether a given IP address is responding with an HTTP error code or is unreachable from a networking standpoint
