### ISSUE TITLE
bug: Adding another Tip Rack does not increment the Tip Rack Name

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5632]
# Overview

Adding another tip rack using the add labware modal does not auto-increment the default tip rack name, unlike when the tip rack is duplicated. All tip racks added in this way have the same default name.  

We'd like to be able to increment for any identical labware.

# Current behavior

![addanothercustomtiprack](https://user-images.githubusercontent.com/579696/81431352-fdc09000-912e-11ea-8c91-23ecd66c8571.gif)

# Steps to reproduce

1. Create a protocol with a custom tip rack
2. On the deck map, click "Add Labware" on any open slot
3. Select the same custom tip rack
4. Do not add a nickname
4. Observe that the names of both tip racks are the same

# Expected behavior

The name of the second tip rack should be auto-incremented with "(1)"

**Comment by shlokamin** [comment]
@howisthisnamenottakenyet @IanLondon @Kadee80 question about this:

This is also the case for non custom labware. I.e. if you add an identical tip rack to the one that's currently on the deck using the `Add Labware` button instead of `Duplicate`, the tip rack name does not get incremented. 

To keep behavior consistent, should we...
(1) Also change this for non custom labware or
(2) Not change anything



<img width="871" alt="Screen Shot 2020-07-01 at 5 21 05 PM" src="https://user-images.githubusercontent.com/5788529/86292763-50627980-bbbf-11ea-8d81-236e55b872a9.png">
