### ISSUE TITLE
PD: new save button behavior

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#5957]
## Try these out in PD:
- Create new protocol. Don't fill in any fields. Note that save button both behaves and looks disabled. Add a pipette but not a tip rack. You will notice that the save button enables. Click the save button. You will notice that fields blur, and the save button takes on a mixed state (looks enabled, but behaves disabled). 
- Open the liquid placement modal in Starting Deck State. Don't input a liquid or volume. Just hit the save button. You will notice that fields blur, and the save button takes on a mixed state (looks enabled, but behaves disabled). 
-Create a Transfer form. Note that the save button both looks and behaves disabled. Fill in the volume field. You will notice that the save button stays disabled. 

There are inconsistencies at the following levels:
- When a form is new does the save button start as enabled or disabled?
- How any of the required fields do you need to fill in before a disabled start button looks enabled? One (New protocol form)? All (Transfer form)?
- When is a save button actually disabled? Styling is not an indicator of behavior. 
- How can a user find out where they are missing required information? Some forms will tell you (by having a save button that blurs pristine fields). Some forms will make you guess.

## Background/Problem statement:

(1) As our forms get increasingly complicated and there's a larger mix of required/non-required form fields, we need a way to help users spot an empty required fields to explain why they can't save the form. 
(2) Currently we regularly have save buttons that are disabled but look enabled. You can click but nothing happens. We don't give any feedback on why the save button isn't working. 

## Design

1. Step is opened (new step, or old step)
2. Save button is styled to be active
3. Clicking the save button blurs all fields for validation. Form is not saved if required info is missing. Save button is styled to be disabled.
4. When all blurred and invalid fields have been addressed, Save button is styled to be enabled. 

Complication 1: When a user creates a new profile step that could introduce new pristine-and-required form fields into a form where the button has been disabled. Would that re-enable it so a user can click and blur all the new form fields?

Complication 2: What is the difficulty level of adding a tooltip to the disabled save button? It would be nice to have a tooltip saying something like "Fill in all required fields".

**Comment by IanLondon** [comment]
> Complication 1: When a user creates a new profile step that could introduce new pristine-and-required form fields into a form where the button has been disabled. Would that re-enable it so a user can click and blur all the new form fields?

I can think of 2 ways to achieve the goal of "clicking the save button when the form has errors ensures all invisible errors are visible":
1. "Dirty" all the fields, so any errors made invisible by pristinity become visible
2. Instead, turn off the error-suppressing system, so pristinity no longer has any effect on error visibility (use a new boolean value "allErrorsShouldBeVisible")

These aren't equivalent, because if we dirty all the fields as in 1, we miss cases where pristinity is re-introduced to a fully-dirtied form. Even when you have all the fields dirty, new dynamic fields added to the form are pristine. Eg adding TC Profile steps/cycles adds temperature/duration/repetitions fields, and they start as pristine.

In a form where the user has already clicked "save" and failed to save because there were errors, do we want the UX to be 1 or 2 here? In both cases, all existing errors are shown immediately upon clicking save (and form doesn't actually save). The difference is what happens later on. When the user adds new **dynamic fields** (eg TC Profile step fields for a new step)...
1. In case 1, The form will not show "required field" etc errors for those new fields. When a field is dirtied and loses its pristinity, then it will always show any errors it has.
2. In case 2, pristinity-related error masking is totally disabled after clicking Save. The new fields will immediately show their errors

If we picked case 1 or case 2 (depends what UX we prefer) then I think we'd un-disable the save button accordingly:
1. In case 1, when there is any pristine field that we can dirty, we need to un-disable the save button so that the user can click it to show potentially hidden errors. So when you add a blank TC profile step, Save will immediately become un-disabled, and clicking it will show you all the "field is required" errors for the fields in that new TC profile step. Maybe we can accomplish this by enabling save only when clicking it would do something? So if you have invisible errors, save button will always be enabled. (If instead visible errors but no invisible errors, save button will always be disabled.) So a disabled save button would become un-disabled when you do anything to cause an invisible error (eg adding a new TC profile step and how filling out the fields).
2. In case 2, field pristinity has already been turned off by clicking the save button once. Clicking the save button further won't do anything -- unless you can actually save. So in case 2, the deactivated save button would only be un-deactivated when you can actually save the form

I think I prefer the UX of case 1, because case 2 is giving up the benefits of pristinity-hides-errors for dynamic fields

> Complication 2: What is the difficulty level of adding a tooltip to the disabled save button? It would be nice to have a tooltip saying something like "Fill in all required fields".

I think it's tricky just to figure out what copy would go in there because there can be multiple errors of different types, eg a required field is missing, and a number is above its max allowed value, and the well source:dest ratio is must be 1:N N:N or N:1.

Maybe we could do a generic "Please address the errors in the form" tooltip, because since all fields have been dirtied by clicking the save button, all error banners will be visible? I'm not sure how the disable save button's tooltip will be helpful since they just echo the error banners. Unless we're planning on getting rid of the error banners?
