### ISSUE TITLE
TC PD UX: Add tooltips to profile buttons

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6062]
## Background
As a user I would like to know the difference between the + STEP and + CYCLE buttons. Screenshot for context. 
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/41b9890c-8d65-4b52-bb86-7225fb4da801)

## Acceptance criteria
- [ ] Add tooltip to + STEP button
- [ ] Add tooltip to + CYCLE button
- [ ] Add tooltip to + STEP button within a cycle

## Copy
- [ ] Copy for + STEP button: "Add a single non-cycling step"
- [ ] Copy for + CYCLE button: "Add a series of steps that cycle"
- [ ] Copy for + STEP button within a cycle: "Add a step to the cycle"

**Comment by pantslakz** [comment]
Since they are already in the context of a profile, we can remove that word. Also to simplify, would recommend we avoid introducing new terms like "together" and "timed", and instead leverage the terminology already present in the button. 

Copy for + STEP button: "Add a single non-cycling step"
 Copy for + CYCLE button: "Add a series of steps that cycle"
 Copy for + STEP button within a cycle: "Add a step to the cycle"
