### ISSUE TITLE
bug: App tells Intercom that unknown users are literally named "Unknown User"

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#6461]
# Overview

* Intercom has a few places that identify users by first name. ("Hi, Max!")
* It has smart fallbacks for when it doesn't know the user's name. ("Hi, there!")
* The app accidentally circumvents those fallbacks by setting the user's full name to "Unknown User":

   <img width="378" alt="Screen Shot 2020-09-01 at 10 16 16 AM" src="https://user-images.githubusercontent.com/3236864/91864658-78fa0480-ec3e-11ea-9f11-40cf02875ce9.png">

   <img width="515" alt="Screen Shot 2020-09-01 at 10 17 28 AM" src="https://user-images.githubusercontent.com/3236864/91864710-8a431100-ec3e-11ea-83d9-36f42fb7b8d4.png">

# Steps to reproduce

1. Get a totally fresh Opentrons App installation. (You'll probably need to delete `Application Support/Opentrons`.)
2. Open a chat.
3. On Intercom, see that this is how you're identified:

<img width="250" alt="Screen Shot 2020-09-01 at 10 21 57 AM" src="https://user-images.githubusercontent.com/3236864/91864125-dfcaee00-ec3d-11ea-98b9-c2968c24b52a.png">

# Current behavior

The app sends this to Intercom upon first contact:

https://github.com/Opentrons/opentrons/blob/1886fd172cfeb2a76e6a165b080c202a5c44cc8b/app-shell/src/config/migrate.js#L66

# Expected behavior

I *think* the app should send `name: null`, but there's also a chance it should send `name: ""`, or even not send a `name` at all. I haven't had a chance to look deeply into Intercom's user attribute semantics.

**Comment by SyntaxColoring** [comment]
As a quick partial fix, I've changed the Intercom chat box welcome message to "Hi there! 👋", ignoring the user's name.

**Comment by mcous** [comment]
This was an intentional decision to address the following:

- We assign a given app installation a unique ID to preserve identity across app openings (see #1999)
- In the absence of a known name or email, Intercom will display that user id in the inbound panel as the users name, which felt annoying at the time

<img width="1792" alt="Screen Shot 2020-09-01 at 13 25 04" src="https://user-images.githubusercontent.com/2963448/91886184-f16cbf80-ec56-11ea-968a-bc77cdc33920.png">

The downsides of assigning the literal "Unknown User" to the name (e.g. having working fallbacks for an unknown name in automatic messages) seem to pretty clearly outweigh the downsides that lead us to implement `Unknown User` in the first place, but we should be aware that **removing the default name will cause UUIDs to be displayed at the users' names on our end**
