### ISSUE TITLE
Calibration: Run app should be able to control jog speed during labware calibration

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#665]
## overview

It is sometimes not clear which setting you are on when jogging the robot.

## behavior

If I double click on the "fast" or "slow" button twice accidentally, it will switch to the opposite setting. This can be confusing as the current graphics are not super clear as to which one is "pressed" and which one is not pressed.

## steps to reproduce

Use the jogger tool, and double click on either setting to see it switch.

---

Edit 2018-02-09 by @mcous:

#783 removed the jog speed controls. This ticket is now tracking the re-addition of those controls pending screens from @Opentrons/design

**Comment by mcous** [comment]
@pantslakz based on slack I'm pretty sure this is already on your radar. This was a engineer special from yours truly. I should note that there's absolutely no technical meaning behind slow and fast, we just picked arbitrary jog distances of 0.25 and 4 mm, respectively. There's also no technical reason to have only two options.

I'm going to remove the "bug" label simply because there's no bug in the code (code is written to toggle distance on on control click, with the non-faded option being the selected on). Perhaps we need a label for bad UX?

**Comment by pantslakz** [comment]
design label should do :P

**Comment by pantslakz** [comment]
@Laura-Danielle how do you feel about removing the "fast/slow" buttons, and in place enabling user to jog in larger increments when holding [SHIFT] + arrow.

**Comment by Laura-Danielle** [comment]
Sorry @pantslakz just seeing this comment for some reason.  Would prefer for the user to just be able to use arrows to jog instead of holding [SHIFT] + arrow. Would also be nice to have more fine-tuning ability on increment changes.

**Comment by mcous** [comment]
Closed by #1223
