### ISSUE TITLE
feat: Python packages for scientific computing (image & data analysis)

### ISSUE THREAD

**Issue by gregorwschmidt** [Opentrons/opentrons#8259]
# Overview

We are organizing a practical course in lab automation for our biotechnology master students using 8x OT2s. The students learn to use the OT2 through the python API. After getting introduced to the basics of pipetting, they are also running some more advanced projects. For these projects we need some additional python libraries installed on the OT2s. The required packages are mainly regarding image analysis (skimage) and data processing (scipy, matplotlib). We need those packages to let the students program a colony picking protocol, which is an integral part of our lab course. We request to install the following packages:

 - skimage
 - matplotlib
 - scipy

There are some additional packages that will be very useful in the future for machine learning (sklearn) and for building nice GUIs (pyside or pyQT). We don't need these packages right now, but we think that they will be also helpful for others. The following packages would be optional:
- sklearn
- pySide6 6.1.2 or pyQT6

# Implementation details

# Design

# Acceptance criteria

**Comment by mcous** [comment]
Hi @gregorwschmidt! Due to space constraints on the OT-2's filesystem / partition map, I don't think we want to add these packages by default due to their specialized nature and the fact that the onboard Raspberry Pi isn't really powerful enough to do machine learning or computer vision well. We are in the process of building out an [HTTP-based protocol API](https://github.com/Opentrons/http-api-beta) that will allow protocol commands to be issued directly from a user's computer, where you have full control over whatever packages you have installed and whatever hardware you would like to attach.

In the mean time, I would recommend forking the [Opentrons/buildroot](https://github.com/Opentrons/buildroot) repository, which builds the OT-2's operating system, including all preinstalled packages. You should be able to build a custom distribution that includes your necessary software for your course, and would provide a path to possibly merge those changes into the main release if we're able to solve the space constraints.

If you have any questions or run into any problems customizing the operating system to your needs, feel free to open an issue in that repository!
