### ISSUE TITLE
How to avoid the simulation of particular lines of a protocol

### ISSUE THREAD

**Issue by multiplex-bio** [Opentrons/opentrons#8332]
I have modified a protocol of the OT-2 robot in which **I want to add a timer to count the minutes passed since the beginning of an incubation**. Here is how I implemented it in python code:

```
from opentrons import protocol_api, types
import time

metadata = {'apiLevel': '2.4'}

def run(protocol_context):
    
    incubation_time = 5
    minutes_passed = 0

    while minutes_passed < incubation_time:
        time.sleep(2) # When I change the 2 to 60 it takes too long to simulate the entire protocol
        minutes_passed += 1
        protocol_context.comment('{} minutes out of {} minutes'.format(minutes_passed, incubation_time))
```

So, when I set the argument of time.sleep() as 2 the simulation runs fast because it only takes 2 seconds to go further in the loop. However, when I change the argument from 2 to 60 (because what I want is to count the number of minutes passed since the beginning of the incubation) the simulation slows down a lot. 

**How can I avoid the simulation of the while loop?** I think that since I know that piece of code is working, it is not important if the robot simulates it before start the protocol every time

Thanks in advance!

**Comment by mcous** [comment]
Hi @multiplex-bio, I have some good news and I have some bad news. Starting with the bad news:

The message passed to `protocol_context.comment` will only ever display the message that was calculated during simulation. It will not be updated during the actual run. This is due to fundamental architectural limitations in the protocol run system, but we're working on fixing this!

The good news: there are a few simple ways to bypass stuff during simulation. For the specific use case of "I want to wait an amount of time," you should use [`protocol_context.delay(...)`](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.ProtocolContext.delay) method rather than `time.sleep`. Otherwise, for a general case solution, you can guard blocks of code using [`protocol_context.is_simulating()`](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.ProtocolContext.is_simulating):

```python
from opentrons.protocol_api import ProtocolContext

def run(protocol_context: ProtocolContext) -> None:
    # ...

    # delay for one minute
    protocol_context.delay(seconds=60, msg="Delaying for 60 seconds")

    # ...

    # do something complex only during the actual run
    if not protocol_context.is_simulating():
        do_something_complex()

    # ...
```
