### ISSUE TITLE
doc: unclear API doc code sample

### ISSUE THREAD

**Issue by splaisan** [Opentrons/opentrons#8415]
Not being a python expert yet, I fully rely on examples to learn programming with the APIP, in some cases the info is not clear, eg: https://docs.opentrons.com/v2/new_atomic_commands.html?highlight=head%20movement#iterating-through-tips

The frankenstein piece of code copied here does not make full sense to me.
What does the s in **s.**bottom(10) mean and is this a standard notation? 
(please change 'm300' to 'pipette' for consistency)

Thanks in advance

```
To check whether you should pick up a tip or not, you can utilize InstrumentContext.has_tip():

for block in range(3):
    if block == 0 and not pipette.has_tip:
        pipette.pick_up_tip()
    else:
        m300.mix(mix_repetitions, 250, d)
        m300.blow_out(s.bottom(10))
        m300.return_tip()

New in version 2.7.
```

**Comment by SyntaxColoring** [comment]
Hi, apologies for not replying to this. I'm sure you've moved on, but for some closure:

In the code you've pasted, the `s` in `m300.blow_out(s.bottom(10))` probably referred to a `Well` that was expected to be defined externally to the example code. I agree it's unclear. I think we've improved our examples quite a bit since this issue was filed. These days, `.bottom()` and `.top()` are described here: https://docs.opentrons.com/v2/robot_position.html?highlight=top#top-bottom-and-center
