### ISSUE TITLE
Labware offsets aren't applied when the connected module doesn't exactly match the loaded module

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#8977]
# Background

Currently, as a hack, this is how applying labware offsets works when the labware is on a module:

1. The protocol analysis completes with a report of where each labware is.
    
    For example, it will report that a labware whose definition URI is`some_namespace/some_load_name/1` is on a module whose ID is `<some-opaque-module-id>`. And, furthermore, the module whose ID is `<some-opaque-module-id>` is a `temperatureModuleV1` on deck slot `1`.

    Note that the module's model—`temperatureModuleV1`, in this case—is only approximate. This is because analysis derives purely from the protocol itself, and not from the hardware that's physically attached to the robot; whereas during the actual run, the Python Protocol API consults the hardware that's physically attached.

      For example, if a protocol loads a `temperatureModuleV1` (spelled `"temperature module"` in the Python Protocol API), but the robot physically is physically connected to a `temperatureModuleV2` (spelled `"temperature module gen2"` in the Python Protocol API), analysis will report a `temperatureModuleV1` but the actual run will report a `temperatureModuleV2`.

2. The client grabs, from that analysis, the labware's definition URI, the module's model, and the module's deck slot.

3. The client chooses what vector to use for the labware offset. It `POST`s that vector with the previously retrieved labware definition URI, module model, and module deck slot.

4. During the run, every time a labware is loaded, the robot software will see if that offset matches. The offset matches if the labware definition URI, module model, and module deck slot are identical.

    If it does match, it will apply the given vector.

# The problem

In step (2), the client grabs a *predicted* module model. But in step (4), the robot compares that with the *physically connected* module model.

If they don't exactly match—for example, if a protocol does `load_module("temperature module")` (v1) but a `temperatureModuleV2` is physically connected, the labware offset will unexpectedly not apply.

To work around this for the beta, we're asking our testers to make sure that the physically connected module strictly matches the predicted module. But this isn't acceptable for public release.

# Acceptance criteria

* Python and JSON protocols that were written to ask for a Temperature Module GEN1, or just a `"temperature module"`, will continue to run when the robot physically has a Temperature Module GEN2 connected instead.
* Offsets created during those runs' Labware Position Check will correctly apply to the run itself.

**Comment by SyntaxColoring** [comment]
Rough solution directions off the top of my head. This list isn't exhaustive.

* We change the Protocol Engine `loadModule` command contract, so that instead of loading an exact, strictly matching `moduleModel`, it's allowed to load any "compatible" model.

   What counts as "compatible" is left for the robot software to decide. 

   The command result would probably include the actually-loaded model, while the requested model could still be retrieved from the request params.

   Internally in the robot software, we update the PAPIv2 legacy command mapper to correctly pass along the requested model *and* loaded model.
   
   We change the labware offset contract so that the client specifies the model that it expects will be *requested,* instead of the model that it expects will be *loaded.*

   We update step (4) so that the server compares the requested model, not the loaded model.

* Something involving an explicit server-provided link between a labware offset and an analyzed resource that the offset is intended to apply to. For example, stable IDs, but there are also other ways of doing this.

**Comment by mattwelch** [comment]
Closed in favor of #8914
