### ISSUE TITLE
Robot analyzes complex protocol very slowly on 5.0.0-beta.x

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9109]
5.0.0-beta.3

* Complex protocol takes 6x longer than on 4.7 to load on beta.3 (also tried on .4).
* After analysis completion, executing `GET /protocol/id` takes ~30 seconds for this 14k-step protocol.

The front-end problem mike noted below is a separate issue, for which @shlokamin already has some proposed solutions.

https://opentrons.slack.com/archives/C02MWV2M18R/p1639518981089000

**Comment by mcous** [comment]
When testing with the dev server, this appears to be an app side issue. On my computer, the protocol can load and simulate properly, but when I click the "Run" tab, the UI effectively freezes. Eventually, the debug console in the app spits out:

```
react_devtools_backend.js:6 Warning: React instrumentation encountered an error: RangeError: Maximum call stack size exceeded
```

My hunch is that this is because the app sends out a `GET` for every single command in the run log upon run page load

**Comment by SyntaxColoring** [comment]
Hypotheses on back-end causes: https://opentrons.slack.com/archives/C01F7KPNASV/p1639596222046500?thread_ts=1639577424.026500&cid=C01F7KPNASV
