### ISSUE TITLE
bug: Distribute incorrectly adds disposal volume when using maximum pipette volume

### ISSUE THREAD

**Issue by danolson1** [Opentrons/opentrons#9112]
# Overview

When I use the distribute command to transfer 20 ul with a p20 pipette, the software splits it up into 2 10 ul transfers.

# Steps to reproduce

`p20.distribute(20, water, assay_plate.wells()[353:380])`
Distributing 20.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 to B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7
Transferring 20.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 to B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7
Picking up tip from A1 of Opentrons 96 Tip Rack 20 µL on 2
Aspirating 11.0 uL from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 at 7.56 uL/sec
Dispensing 10.0 uL into B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7 at 7.56 uL/sec
Blowing out at A1 of Opentrons Fixed Trash on 12
Aspirating 11.0 uL from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 at 7.56 uL/sec
Dispensing 10.0 uL into B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7 at 7.56 uL/sec
Blowing out at A1 of Opentrons Fixed Trash on 12

`p20.transfer(20, water, assay_plate.wells()[353:380])`
Transferring 20.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 to B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7
Picking up tip from A1 of Opentrons 96 Tip Rack 20 µL on 2
Aspirating 20.0 uL from A1 of USA Scientific 12 Well Reservoir 22 mL on 5 at 7.56 uL/sec
Dispensing 20.0 uL into B23 of Corning 384 Well Plate 112 µL Flat on Temperature Module GEN2 on 7 at 7.56 uL/sec

# Current behavior

In this case, dispense and transfer give different results.

# Expected behavior

I would expect them to give the same result.

**Comment by mcous** [comment]
"Unecessary" blow-outs from the `distribute` command are tracked in #8315 and #3117, so I'm going to close this ticke. In general, you should not expect the same results between `transfer` and `distribute` (otherwise we wouldn't have two different methods 😄). Unless you specifically want to aspirate a large amount of liquid once and then dispense that one large blob of liquid into multiple wells, you should not use `distribute`.

From your example, I think you're trying to do a one-to-many transfer, where each transfer is a single aspirate from the source well followed by a single dispense into the destination well. As detailed in the [complex commands documentation](https://docs.opentrons.com/v2/new_complex_commands.html), the appropriate method to use here is `transfer`, not `distribute`.
