### ISSUE TITLE
bug: set_rail_lights() doesn't work via Jupyter interface 

### ISSUE THREAD

**Issue by danolson1** [Opentrons/opentrons#9139]
# Overview
I can't seem to turn the rail lights on an off using the Jupyter interface, despite the other commands functioning correctly.

I get the following error message, which may be relevant.
```
/data/robot_settings.json not found. Loading defaults
/data/deck_calibration.json not found. Loading defaults
```

# Steps to reproduce

```
import opentrons.execute
from opentrons import protocol_api, simulate, types

metadata = {'apiLevel': '2.11',
            'author'  : 'Dan Olson'}

live_protocol = opentrons.execute.get_protocol_api('2.11') # the live protocol
live_protocol.set_rail_lights(True) 
```

# Current behavior
Rail lights stay off

# Expected behavior
Rail lights should have turned on

**Comment by mcous** [comment]
This is expected if the robot's HTTP server is running while you are using Jupyter, since only one piece of software is allowed to fully control the device's hardware at a given moment in time. If this is the case, you will see the following warning printed in Jupyter.

> Loading defaults Failed to initialize character device, will not be able to control gpios (lights, button, smoothiekill, smoothie reset). Only one connection can be made to the gpios at a time. If you need to control gpios, first stop the robot server with systemctl stop opentrons-robot-server. Until you restart the server with systemctl start opentrons-robot-server, you will be unable to control the robot using the Opentrons app.

If you see this message and need to control the lights, you should follow the instructions in the warning and issue `systemctl stop opentrons-robot-server` via Jupyter's terminal so that your Jupyter protocol can fully control the hardware
