### ISSUE TITLE
LPC run even for labware not used by protocol

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9166]
From a user:
"Position offset check would not save and now included every labware I had in my script and not just the labware. No longer testing tip pickup for the first tiprack ( I like to do that because of previous issues with calibration). Does not home after offset checks."

What he means by "included every labware" is that he specified labware at the top of his protocol that he never actually uses (perhaps commenting out its usage). He notes that this labware insists on being position checked. He believes that calibration was NOT run on this type of labware in 4.x.

Contact Matt for a copy of the protocol

**Comment by mcous** [comment]
This is an intentional (breaking) change from old, inconsistent behavior, where one could issue a labware load but never “use” the labware. Moving forward in 5.0, all labware loaded in a protocol will be considered used. If a Python protocol is parametrized in this way, it should be written to avoid calling ctx.load_labware for anything unused
