### ISSUE TITLE
Send G-Code to OT2 

### ISSUE THREAD

**Issue by ajbarrett** [Opentrons/opentrons#9411]
# Overview
Hello, so I have spent a couple days digging through the API trying to find a way that allows the mount on the OT2 to move in a circle. To do this, I could theoretically use just a couple G02 commands, which create circular motion. So, I am trying to feed G-code to the machine. 

The OT2 already has a SmoothieDriver class in the "driver_3_0.py" file which takes uses G-code to create movement. We really don't want to have to re-invent the wheel here, so we would like to use the driver that already exists. 

I am thinking that there has to be a way to talk to the SmoothieDriver object that already exists in memory. I am assuming it has to be somewhere buried in the ProtocolContext object. Is there any low-hanging fruit that would allow me to pass just a couple G-code commands to the robot? Any help is deeply appreciated!

Note:
The "move_to" command is not sufficient. The motion is very jerky as the robot speeds up and comes to a full stop in-between points on the circle.

**Comment by mcous** [comment]
We do not use circular motion commands on the OT-2 nor do we support them. We cannot support nor in any way guarantee that they will work.

Issuing G-code directly to the motor controller is possible in the technical sense, but raises the possibility of all sorts of things going wrong due to the bypass of both protocol and hardware controller state. Additionally, the coordinate system that the motor controller board uses is not the same as the coordinate system used by the higher-level hardware control system, which does stuff like account for deck warping and leveling.

As of the 4.7 release, I believe you could access the Smoothie driver directly through various private properties. **This may or may not work**, and it is not supported nor recommended by Opentrons. Additionally, all these interfaces are very private, internal interfaces, so even if this did work, any or all of these properties are subject to change or removal without warning or notice.

```python
from opentrons.protocol_api import ProtocolContext

...

def run(ctx: ProtocolContext) -> None:
    motor_driver = ctx._hw_manager.hardware._backend._smoothie_driver
    ...
```

In the quite likely event that the snippet above doesn't work, I would recommend you:

1. [SSH into your OT-2](https://support.opentrons.com/en/articles/3203681-setting-up-ssh-access-to-your-ot-2)
2. Stop the Opentrons service and hardware controller with `systemctl stop opentrons-robot-server`
    - This will render the Opentrons App unable to talk to your robot until you reboot the OT-2
3. Write your own Python application that imports what you need from the `opentrons` package (e.g. the Smoothie driver) and devise a custom hardware control interface for your needs.

I'm going to close this ticket because we have no intention of implementing g-code in our public Python or hardware controls APIs. Feel free to continue posting questions in this thread, though, and I or one of my colleagues will do our best to answer them.
